apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-postgresql
  template:
    metadata:
      labels:
        app: mlflow-postgresql
    spec:
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: mlflow-postgres-pvc
      containers:
        - name: postgresql
          image: registry.redhat.io/rhel8/postgresql-13:1-101
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: mlflow-postgres-secret
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/pgsql/data
          readinessProbe:
            exec:
              command:
                - /usr/libexec/check-container
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - /usr/libexec/check-container
                - "--live"
            initialDelaySeconds: 120
            periodSeconds: 10
