apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ml   # ðŸ‘ˆ OK QUI

resources:
  - namespace.yaml

  # workload applicativi
  - ../../catalog/serving/granite/v1
  - ../../catalog/object-storage/minio/v1

  # RBAC applicativo
  - ../../catalog/rbac/admin/v1

  # segreti
  - secrets/minio-secret.yaml

patches:
  - path: patches/granite-patch.yaml
  - path: patches/minio-patch.yaml
