apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ml   # ðŸ‘ˆ QUESTO Ãˆ IL FIX CHIAVE

resources:
  - namespace.yaml

  # piattaforma
  - ../../catalog/serving/granite/v1
  - ../../catalog/object-storage/minio/v1

  # operatori
  - ../../catalog/operators/redis-enterprise/v1

  # RBAC
  - ../../catalog/rbac/admin/v1
  - ../../catalog/rbac/admin-redisns/v1

  # segreti
  - secrets/minio-secret.yaml

patches:
  - path: patches/granite-patch.yaml
  - path: patches/minio-patch.yaml
  - path: patches/rbac-redisns-patch.yaml
