apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces/mlops-user-b.yaml

  # base MLOps
  - ../../../modules/minio/v1
  - ../../modules/workbench/v1
  - ../../modules/pipelines/v1

  # ❌ niente MLflow
  # ❌ niente Redis
  # ❌ niente Monitoring (per ora)
