apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ds-prometheus
  namespace: monitoring-tools
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Thanos-Monitoring
        type: prometheus
        access: proxy
        url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
        isDefault: true
        jsonData:
          tlsSkipVerify: true
          httpMethod: GET
          httpHeaderName1: Authorization
          timeInterval: "30s"
        secureJsonData:
          httpHeaderValue1: "Bearer ${PROM_TOKEN}"
