apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-tools

resources:
  - sa-token-refresher.yaml
  - grafana.yaml
  - datasource-prometheus.yaml
  - grafana-ds-mlflow.yaml
  - grafana-dashboard-providers.yaml
  - secret-prometheus-token.yaml
  - rbac-token-refresher.yaml
  - cronjob-token-refresher.yaml
  - rbac-grafana-prometheus.yaml

configMapGenerator:
  - name: grafana-dashboard-mlflow
    files:
      - dashboards/mlflow-training-dashboard.json

  - name: grafana-dashboard-vllm
    files:
      - dashboards/vllm-dashboard.json

  - name: grafana-dashboard-otel-ml
    files:
      - dashboards/otel-ml-training-dashboard.json

generatorOptions:
  disableNameSuffixHash: true

