apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-sa-prometheus-reader
subjects:
  - kind: ServiceAccount
    name: grafana-sa
    namespace: monitoring-tools
roleRef:
  kind: ClusterRole
  name: cluster-monitoring-view
  apiGroup: rbac.authorization.k8s.io
