apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana-token-refresher-role
  namespace: monitoring-tools
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "update", "patch"]

  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    verbs: ["create"]

  # ðŸ‘‡ PERMESSI MANCANTI PER ELIMINARE POD
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-token-refresher-rb
  namespace: monitoring-tools
subjects:
  - kind: ServiceAccount
    name: grafana-token-refresher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grafana-token-refresher-role
