apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces/mlops.yaml
  - rbac/user-access.yaml
  - rbac/redis-access.yaml

  # moduli   
  - mlops
  - redis
  - redis-operator
  - monitoring-tools


  
