apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlops-user-a

resources:
  - namespace.yaml
  - ../../platform
  - ../../modules/minio/v1
  - ../../modules/workbench/v1
  - ../../modules/pipelines/v1
  - ../../modules/inference/granite-3-1-2b/v1
  - ../../modules/serving-runtime/granite/v1
  - ../../modules/redis/enterprise/v1
