apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces/mlops.yaml
  - mlops
  - redis
  - redis-operator
  - ../../modules/mlflow/v1
  - secrets/mlflow-backend-secret.yaml
  
